import type { Course, CourseId, Seg } from "./types";

export const TILE = 48;

function track(segs: Seg[]): Seg[] {
  return segs;
}

export const COURSES: Course[] = [
  {
    id: "roll-out",
    name: "First Trace",
    blurb: "Berty auto-runs the copper. Space or tap to jump. Grab every bit. Hit the gate.",
    par: 42,
    segs: track([
      { k: "g", w: 980 },
      { k: "gems", n: 4, form: "line" },
      { k: "g", w: 80 },
      { k: "crate" },
      { k: "g", w: 220 },
      { k: "gems", n: 3, form: "arc" },
      { k: "g", w: 40 },
      { k: "gap", w: 150 },
      { k: "g", w: 280 },
      { k: "check" },
      { k: "g", w: 160 },
      { k: "crate" },
      { k: "g", w: 180 },
      { k: "saw" },
      { k: "g", w: 240 },
      { k: "gems", n: 4, form: "line" },
      { k: "g", w: 80 },
      { k: "gap", w: 170 },
      { k: "g", w: 220 },
      { k: "check" },
      { k: "g", w: 140 },
      { k: "crate" },
      { k: "g", w: 90 },
      { k: "crate" },
      { k: "g", w: 200 },
      { k: "gems", n: 5, form: "high" },
      { k: "g", w: 80 },
      { k: "saw", h: 70 },
      { k: "g", w: 260 },
      { k: "gap", w: 160 },
      { k: "g", w: 300 },
      { k: "gems", n: 6, form: "line" },
      { k: "g", w: 420 },
      { k: "gate" },
    ]),
  },
  {
    id: "mind-the-pit",
    name: "Mind the Pit",
    blurb: "Empty sockets swallow a late jump. Hit the checkpoint. Stay on the copper.",
    par: 48,
    segs: track([
      { k: "g", w: 720 },
      { k: "gems", n: 3, form: "line" },
      { k: "g", w: 40 },
      { k: "gap", w: 170 },
      { k: "g", w: 200 },
      { k: "crate" },
      { k: "g", w: 80 },
      { k: "gap", w: 160 },
      { k: "g", w: 180 },
      { k: "check" },
      { k: "g", w: 120 },
      { k: "saw" },
      { k: "g", w: 90 },
      { k: "gap", w: 180 },
      { k: "g", w: 160 },
      { k: "gems", n: 4, form: "arc" },
      { k: "g", w: 60 },
      { k: "crate" },
      { k: "g", w: 70 },
      { k: "gap", w: 190 },
      { k: "g", w: 240 },
      { k: "check" },
      { k: "g", w: 100 },
      { k: "saw", h: 78 },
      { k: "g", w: 80 },
      { k: "crate" },
      { k: "g", w: 80 },
      { k: "gap", w: 170 },
      { k: "g", w: 280 },
      { k: "gems", n: 5, form: "line" },
      { k: "g", w: 360 },
      { k: "gate" },
    ]),
  },
  {
    id: "saw-line",
    name: "Fan Line",
    blurb: "Cooling fans do not wait. Time the jump. Bits first, then the gate.",
    par: 50,
    segs: track([
      { k: "g", w: 700 },
      { k: "gems", n: 3, form: "line" },
      { k: "saw" },
      { k: "g", w: 180 },
      { k: "saw", h: 64 },
      { k: "g", w: 200 },
      { k: "check" },
      { k: "g", w: 80 },
      { k: "crate" },
      { k: "g", w: 70 },
      { k: "saw" },
      { k: "g", w: 160 },
      { k: "gap", w: 150 },
      { k: "g", w: 140 },
      { k: "gems", n: 4, form: "arc" },
      { k: "saw", h: 80 },
      { k: "g", w: 180 },
      { k: "check" },
      { k: "g", w: 100 },
      { k: "saw" },
      { k: "g", w: 80 },
      { k: "saw", h: 70 },
      { k: "g", w: 200 },
      { k: "gap", w: 170 },
      { k: "g", w: 280 },
      { k: "gems", n: 5, form: "line" },
      { k: "g", w: 340 },
      { k: "gate" },
    ]),
  },
  {
    id: "oil-pan",
    name: "Thermal Paste",
    blurb: "Same jump. Tighter gaps. Boost pads shove you forward.",
    par: 46,
    segs: track([
      { k: "g", w: 640 },
      { k: "boost" },
      { k: "g", w: 80 },
      { k: "gems", n: 3, form: "high" },
      { k: "gap", w: 180 },
      { k: "g", w: 160 },
      { k: "crate" },
      { k: "g", w: 70 },
      { k: "gap", w: 170 },
      { k: "g", w: 160 },
      { k: "check" },
      { k: "boost" },
      { k: "g", w: 60 },
      { k: "saw" },
      { k: "g", w: 90 },
      { k: "crate" },
      { k: "g", w: 80 },
      { k: "gap", w: 185 },
      { k: "g", w: 200 },
      { k: "check" },
      { k: "g", w: 80 },
      { k: "gems", n: 5, form: "arc" },
      { k: "saw", h: 76 },
      { k: "g", w: 120 },
      { k: "gap", w: 160 },
      { k: "g", w: 300 },
      { k: "gems", n: 4, form: "line" },
      { k: "g", w: 320 },
      { k: "gate" },
    ]),
  },
  {
    id: "crew-gate",
    name: "Crew Gate",
    blurb: "Solo this period: one button, one Berty. Tight rhythm into the port.",
    par: 52,
    segs: track([
      { k: "g", w: 620 },
      { k: "gems", n: 3, form: "line" },
      { k: "crate" },
      { k: "g", w: 60 },
      { k: "saw" },
      { k: "g", w: 70 },
      { k: "gap", w: 165 },
      { k: "g", w: 140 },
      { k: "check" },
      { k: "crate" },
      { k: "g", w: 50 },
      { k: "crate" },
      { k: "g", w: 70 },
      { k: "saw", h: 72 },
      { k: "g", w: 90 },
      { k: "gap", w: 175 },
      { k: "g", w: 160 },
      { k: "check" },
      { k: "gems", n: 4, form: "high" },
      { k: "saw" },
      { k: "g", w: 70 },
      { k: "crate" },
      { k: "g", w: 60 },
      { k: "gap", w: 180 },
      { k: "g", w: 80 },
      { k: "saw", h: 80 },
      { k: "g", w: 240 },
      { k: "gems", n: 6, form: "line" },
      { k: "g", w: 360 },
      { k: "gate" },
    ]),
  },
  {
    id: "around-the-bend",
    name: "Around the Bend",
    blurb: "Longer copper. Jump on the beat. Boost, then a late fan.",
    par: 54,
    segs: track([
      { k: "g", w: 800 },
      { k: "gems", n: 4, form: "line" },
      { k: "g", w: 40 },
      { k: "crate" },
      { k: "g", w: 160 },
      { k: "gap", w: 160 },
      { k: "g", w: 180 },
      { k: "boost" },
      { k: "g", w: 80 },
      { k: "saw" },
      { k: "g", w: 180 },
      { k: "check" },
      { k: "crate" },
      { k: "g", w: 80 },
      { k: "gap", w: 175 },
      { k: "g", w: 140 },
      { k: "gems", n: 4, form: "arc" },
      { k: "saw", h: 74 },
      { k: "g", w: 160 },
      { k: "check" },
      { k: "g", w: 80 },
      { k: "crate" },
      { k: "g", w: 60 },
      { k: "saw" },
      { k: "g", w: 70 },
      { k: "gap", w: 185 },
      { k: "g", w: 280 },
      { k: "gems", n: 5, form: "line" },
      { k: "g", w: 400 },
      { k: "gate" },
    ]),
  },
  {
    id: "pit-drop",
    name: "Pit Drop",
    blurb: "Skinny traces over the void. Jump the pits. Checkpoint after the pinch.",
    par: 50,
    segs: track([
      { k: "g", w: 560 },
      { k: "gems", n: 3, form: "line" },
      { k: "gap", w: 175 },
      { k: "g", w: 140 },
      { k: "gap", w: 165 },
      { k: "g", w: 160 },
      { k: "check" },
      { k: "crate" },
      { k: "g", w: 70 },
      { k: "gap", w: 180 },
      { k: "g", w: 120 },
      { k: "saw" },
      { k: "g", w: 80 },
      { k: "gap", w: 170 },
      { k: "g", w: 180 },
      { k: "check" },
      { k: "gems", n: 4, form: "high" },
      { k: "gap", w: 185 },
      { k: "g", w: 140 },
      { k: "crate" },
      { k: "g", w: 60 },
      { k: "gap", w: 175 },
      { k: "g", w: 260 },
      { k: "gems", n: 4, form: "line" },
      { k: "g", w: 320 },
      { k: "gate" },
    ]),
  },
  {
    id: "blade-walk",
    name: "Blade Walk",
    blurb: "Fans stacked on the beat. Jump, land, jump.",
    par: 52,
    segs: track([
      { k: "g", w: 620 },
      { k: "saw" },
      { k: "g", w: 140 },
      { k: "saw", h: 68 },
      { k: "g", w: 150 },
      { k: "saw" },
      { k: "g", w: 180 },
      { k: "check" },
      { k: "gems", n: 3, form: "arc" },
      { k: "saw", h: 76 },
      { k: "g", w: 90 },
      { k: "crate" },
      { k: "g", w: 70 },
      { k: "saw" },
      { k: "g", w: 160 },
      { k: "check" },
      { k: "gap", w: 160 },
      { k: "g", w: 100 },
      { k: "saw", h: 80 },
      { k: "g", w: 80 },
      { k: "saw" },
      { k: "g", w: 200 },
      { k: "gems", n: 5, form: "line" },
      { k: "g", w: 340 },
      { k: "gate" },
    ]),
  },
  {
    id: "slick-shelf",
    name: "Slick Shelf",
    blurb: "Boosts plus late jumps. Do not tap early.",
    par: 48,
    segs: track([
      { k: "g", w: 600 },
      { k: "boost" },
      { k: "g", w: 40 },
      { k: "gap", w: 190 },
      { k: "g", w: 160 },
      { k: "crate" },
      { k: "boost" },
      { k: "g", w: 40 },
      { k: "saw" },
      { k: "g", w: 180 },
      { k: "check" },
      { k: "gems", n: 4, form: "high" },
      { k: "gap", w: 175 },
      { k: "g", w: 120 },
      { k: "boost" },
      { k: "crate" },
      { k: "g", w: 70 },
      { k: "gap", w: 180 },
      { k: "g", w: 180 },
      { k: "check" },
      { k: "saw", h: 78 },
      { k: "g", w: 90 },
      { k: "gap", w: 170 },
      { k: "g", w: 260 },
      { k: "gems", n: 5, form: "line" },
      { k: "g", w: 320 },
      { k: "gate" },
    ]),
  },
  {
    id: "shop-exit",
    name: "I/O Exit",
    blurb: "Finale. Mix of pits, fans, and crates. Port at the end.",
    par: 58,
    segs: track([
      { k: "g", w: 700 },
      { k: "gems", n: 4, form: "line" },
      { k: "crate" },
      { k: "g", w: 70 },
      { k: "saw" },
      { k: "g", w: 80 },
      { k: "gap", w: 170 },
      { k: "g", w: 150 },
      { k: "check" },
      { k: "boost" },
      { k: "g", w: 50 },
      { k: "crate" },
      { k: "g", w: 50 },
      { k: "crate" },
      { k: "g", w: 70 },
      { k: "saw", h: 74 },
      { k: "g", w: 80 },
      { k: "gap", w: 180 },
      { k: "g", w: 160 },
      { k: "check" },
      { k: "gems", n: 4, form: "arc" },
      { k: "saw" },
      { k: "g", w: 60 },
      { k: "gap", w: 175 },
      { k: "g", w: 90 },
      { k: "saw", h: 80 },
      { k: "g", w: 70 },
      { k: "crate" },
      { k: "g", w: 70 },
      { k: "gap", w: 185 },
      { k: "g", w: 260 },
      { k: "gems", n: 6, form: "line" },
      { k: "g", w: 400 },
      { k: "gate" },
    ]),
  },
];

export function courseById(id: CourseId): Course {
  const found = COURSES.find((c) => c.id === id);
  if (!found) throw new Error(`Unknown course ${id}`);
  return found;
}

export function starsFor(time: number, par: number) {
  if (time <= par * 0.75) return 3;
  if (time <= par) return 2;
  return 1;
}

export function starsFromBest(best: number | null | undefined, par: number) {
  if (best == null) return 0;
  return starsFor(best, par);
}

export function fmtTime(t: number) {
  const m = Math.floor(t / 60);
  const s = t % 60;
  return `${m}:${s.toFixed(1).padStart(4, "0")}`;
}
