import { ACCESS_UI } from "@/game/access";
import { courseForPart, nextPart, PARTS } from "@/game/curriculum";
import { shared, type Lang } from "@/game/hub";

type DriveId = "lean" | "hands" | "keys" | "follow" | "tilt";
type Ui = {
  [K in keyof (typeof ACCESS_UI)["en"]]: (typeof ACCESS_UI)["en"][K] extends string
    ? string
    : (typeof ACCESS_UI)["en"][K] extends Record<infer Id, infer Row>
      ? { [P in Id & string]: Row extends string ? string : { name: string; line: string } }
      : (typeof ACCESS_UI)["en"][K];
};

export type Screen = {
  coin: string;
  stageClear: string;
  yourReward: string;
  youWon: string;
  practiceClear: string;
  bits: string;
  star: string;
  stars: string;
  underPar: string;
  overPar: string;
  runAgain: string;
  backBoards: string;
  learnPart: string;
  installPart: string;
  saveOk: string;
  saveNo: string;
  paused: string;
  clockStopped: string;
  boards: string;
  unmute: string;
  loading: string;
  oneQuestion: string;
  goalKicker: string;
  goalTitle: string;
  goalLine: string;
  goalGaming: string;
  goalGamingLine: string;
  goalCreator: string;
  goalCreatorLine: string;
  goalLaptop: string;
  goalLaptopLine: string;
  moreWins: string;
  allPowers: string;
  turnsOn: string;
  zapStill: string;
  yours: string;
  soon: string;
  powers: string;
  whatTheyDo: string;
  allOn: string;
  win: string;
  wins: string;
  newOn: string;
  onComputer: string;
  outHearts: string;
  gameOver: string;
  tryAgain: string;
  holes: string;
  early3d: string;
  score: string;
  great: string;
  perfect: string;
  continueQ: string;
  newHigh: string;
  ready: string;
  go: string;
  locked: string;
  speaks: string;
  readSaid: string;
  courses: string;
  alreadyOn: string;
  nextReward: string;
  everyWon: string;
  bootPc: string;
  cheer1: string;
  cheer2: string;
  cheer3: string;
  cheerN: string;
  cheer0: string;
  watts: string;
};

const EN: Screen = {
  coin: "INSERT COIN / TAP TO START",
  stageClear: "Stage clear",
  yourReward: "Your reward",
  youWon: "You won. This part is yours. Watts pay to put it in the case.",
  practiceClear: "Practice clear. The real boards are in the list.",
  bits: "bits",
  star: "star",
  stars: "stars",
  underPar: "Under par",
  overPar: "Over par",
  runAgain: "Run this board again",
  backBoards: "Back to boards",
  learnPart: "Learn {part}",
  installPart: "Install {part}",
  saveOk: "Saved. This file has every short name on this computer.",
  saveNo: "Save canceled.",
  paused: "Paused",
  clockStopped: "The clock is stopped.",
  boards: "Boards",
  unmute: "Unmute",
  loading: "Loading the board…",
  oneQuestion: "One question. Then you roll.",
  goalKicker: "Help Berty",
  goalTitle: "He is learning the computer.",
  goalLine: "You help Berty. Pick the PC you want.",
  goalGaming: "Gaming PC",
  goalGamingLine: "Fast games. Watch the GPU and the heat.",
  goalCreator: "Creator PC",
  goalCreatorLine: "Pictures, music, and video. Watch storage and the GPU.",
  goalLaptop: "Laptop",
  goalLaptopLine: "Same parts. Small, light, and cool enough to hold.",
  moreWins: "{n} more {unit}",
  allPowers: "All powers on",
  turnsOn: "{name} turns on by itself.",
  zapStill: "Zap is still a button.",
  yours: "Yours",
  soon: "Next",
  powers: "Berty's powers",
  whatTheyDo: "What they do",
  allOn: "All on",
  win: "win",
  wins: "wins",
  newOn: "New on Berty",
  onComputer: "{place} on this computer",
  outHearts: "Out of hearts",
  gameOver: "Game over",
  tryAgain: "Try again",
  holes: "Holes cost a heart. Three misses end the run.",
  early3d: "Early 3D boards put you back on the path. Later ones, a fall costs a heart.",
  score: "Score",
  great: "Great!",
  perfect: "Perfect!",
  continueQ: "Continue?",
  newHigh: "New high score",
  ready: "Ready",
  go: "Go",
  locked: "Locked",
  speaks: "Berty's Run speaks your language, start to results.",
  readSaid: "Read aloud is on.",
  courses: "Courses",
  alreadyOn: "+{n} watts. Berty's PC is already on.",
  nextReward: "+{n} watts. Next reward: {part} ({cost}). You have {watts}.",
  everyWon: "Every part is won. Install {part} with watts.",
  bootPc: "+{n} watts. Every part is in. Boot the PC.",
  cheer1: "I stuck {name} on the top shelf. You are first.",
  cheer2: "Second on {name}. I can hear the one ahead of you.",
  cheer3: "Third on {name}. I wrote your short name on the board.",
  cheerN: "{place} on {name}. Back will not erase it.",
  cheer0: "I pocketed the bits from {name}. Your stars stay if you hit Back.",
  watts: "watts",
};

const SIMPLE: Screen = {
  ...EN,
  coin: "TAP TO START",
  stageClear: "You cleared it",
  yourReward: "Your prize",
  youWon: "You won this part. Watts pay to put it in the case.",
  practiceClear: "Practice is done. The real boards are in the list.",
  runAgain: "Run this board again",
  clockStopped: "The clock is stopped.",
  oneQuestion: "One question. Then you roll.",
  goalTitle: "He is learning the computer.",
  goalLine: "Help Berty. Pick a PC.",
  speaks: "Berty's Run speaks your language, from the start to the end.",
  readSaid: "Read aloud is on.",
  holes: "Holes cost a heart. Three misses end the run.",
};

const ES: Screen = {
  ...EN,
  coin: "METE MONEDA / TOCA PARA EMPEZAR",
  stageClear: "Tablero listo",
  yourReward: "Tu premio",
  youWon: "Ganaste. Esta pieza es tuya. Los vatios pagan para ponerla en la caja.",
  practiceClear: "Práctica lista. Los tableros de verdad están en la lista.",
  bits: "datos",
  star: "estrella",
  stars: "estrellas",
  underPar: "Bajo la marca",
  overPar: "Sobre la marca",
  runAgain: "Correr este tablero otra vez",
  backBoards: "Volver a los tableros",
  learnPart: "Aprender {part}",
  installPart: "Poner {part}",
  saveOk: "Guardado. Este archivo tiene cada nombre corto de esta computadora.",
  saveNo: "Guardado cancelado.",
  paused: "En pausa",
  clockStopped: "El reloj está parado.",
  boards: "Tableros",
  unmute: "Con sonido",
  loading: "Cargando el tablero…",
  oneQuestion: "Una pregunta. Luego ruedas.",
  goalKicker: "Ayuda a Berty",
  goalTitle: "Está aprendiendo la computadora.",
  goalLine: "Tú ayudas a Berty. Elige la PC que quieres.",
  goalGaming: "PC de juegos",
  goalGamingLine: "Juegos rápidos. Mira la GPU y el calor.",
  goalCreator: "PC de crear",
  goalCreatorLine: "Fotos, música y video. Mira el disco y la GPU.",
  goalLaptop: "Portátil",
  goalLaptopLine: "Las mismas piezas. Pequeña, ligera y fresca.",
  allPowers: "Todos los poderes",
  turnsOn: "{name} se enciende solo.",
  zapStill: "Zap sigue siendo un botón.",
  yours: "Tuyo",
  soon: "Siguiente",
  powers: "Poderes de Berty",
  whatTheyDo: "Qué hacen",
  allOn: "Todos",
  win: "logro",
  wins: "logros",
  newOn: "Nuevo en Berty",
  onComputer: "{place} en esta computadora",
  outHearts: "Sin corazones",
  gameOver: "Fin del juego",
  tryAgain: "Otra vez",
  holes: "Los huecos cuestan un corazón. Tres fallos acaban la vuelta.",
  early3d: "Los tableros 3D fáciles te vuelven al camino. Más adelante, una caída cuesta un corazón.",
  score: "Puntos",
  great: "¡Bien!",
  perfect: "¡Perfecto!",
  continueQ: "¿Seguir?",
  newHigh: "Nuevo récord",
  ready: "Listo",
  go: "Ya",
  locked: "Cerrado",
  speaks: "Berty's Run habla tu idioma, del inicio a los resultados.",
  readSaid: "Lectura activada.",
  courses: "Tableros",
  alreadyOn: "+{n} vatios. La PC de Berty ya está encendida.",
  nextReward: "+{n} vatios. Siguiente premio: {part} ({cost}). Tienes {watts}.",
  everyWon: "Todas las piezas están ganadas. Pon {part} con vatios.",
  bootPc: "+{n} vatios. Todas las piezas están. Enciende la PC.",
  cheer1: "Dejé {name} en el estante de arriba. Vas primero.",
  cheer2: "Segundo en {name}. Oigo al que va delante.",
  cheer3: "Tercero en {name}. Escribí tu nombre corto en el tablero.",
  cheerN: "{place} en {name}. Volver no lo borra.",
  cheer0: "Guardé los datos de {name}. Tus estrellas se quedan si vuelves.",
  watts: "vatios",
};

const UK: Screen = {
  ...EN,
  coin: "КИНЬ МОНЕТУ / ТОРКНИСЬ, ЩОБ ПОЧАТИ",
  stageClear: "Етап пройдено",
  yourReward: "Твоя нагорода",
  youWon: "Ти виграв. Ця деталь твоя. Вати платять, щоб поставити її в корпус.",
  practiceClear: "Тренування пройдено. Справжні дошки в списку.",
  bits: "біти",
  star: "зірка",
  stars: "зірки",
  underPar: "Краще за пар",
  overPar: "Гірше за пар",
  runAgain: "Ще раз ця дошка",
  backBoards: "Назад до дошок",
  learnPart: "Вчити {part}",
  installPart: "Поставити {part}",
  saveOk: "Збережено. У файлі кожне коротке ім'я з цього комп'ютера.",
  saveNo: "Збереження скасовано.",
  paused: "Пауза",
  clockStopped: "Годинник стоїть.",
  boards: "Дошки",
  unmute: "Звук",
  loading: "Дошка вантажиться…",
  oneQuestion: "Одне питання. Потім котиш.",
  goalKicker: "Допоможи Берті",
  goalTitle: "Він учиться, як працює комп'ютер.",
  goalLine: "Ти допомагаєш Берті. Обери ПК.",
  goalGaming: "Ігровий ПК",
  goalGamingLine: "Швидкі ігри. Стеж за GPU і теплом.",
  goalCreator: "ПК для творчості",
  goalCreatorLine: "Фото, музика і відео. Стеж за диском і GPU.",
  goalLaptop: "Ноутбук",
  goalLaptopLine: "Ті самі деталі. Малий, легкий і не гарячий.",
  allPowers: "Усі сили ввімкнені",
  turnsOn: "{name} вмикається сам.",
  zapStill: "Зап і далі кнопка.",
  yours: "Твоє",
  soon: "Далі",
  powers: "Сили Берті",
  whatTheyDo: "Що вони роблять",
  allOn: "Усі",
  win: "перемога",
  wins: "перемоги",
  newOn: "Нове в Берті",
  onComputer: "{place} на цьому комп'ютері",
  outHearts: "Серця закінчились",
  gameOver: "Кінець гри",
  tryAgain: "Ще раз",
  holes: "Ями коштують серце. Три промахи кінчають забіг.",
  early3d: "Легкі 3D дошки повертають тебе на шлях. Далі падіння коштує серце.",
  score: "Рахунок",
  great: "Клас!",
  perfect: "Ідеально!",
  continueQ: "Далі?",
  newHigh: "Новий рекорд",
  ready: "Готовий",
  go: "Руш",
  locked: "Закрито",
  speaks: "Berty's Run говорить твоєю мовою, від старту до результатів.",
  readSaid: "Читання вголос увімкнено.",
  courses: "Дошки",
  alreadyOn: "+{n} ват. ПК Берті вже ввімкнений.",
  nextReward: "+{n} ват. Наступна нагорода: {part} ({cost}). У тебе {watts}.",
  everyWon: "Усі деталі виграні. Постав {part} за вати.",
  bootPc: "+{n} ват. Усі деталі всередині. Увімкни ПК.",
  cheer1: "Я поставив {name} на верхню полицю. Ти перший.",
  cheer2: "Другий на {name}. Я чую того, хто попереду.",
  cheer3: "Третій на {name}. Я написав твоє коротке ім'я на дошці.",
  cheerN: "{place} на {name}. Назад цього не зітре.",
  cheer0: "Я забрав біти з {name}. Зірки лишаться, якщо натиснеш Назад.",
  watts: "ват",
};

const RU: Screen = {
  ...EN,
  coin: "БРОСЬ МОНЕТУ / КОСНИСЬ, ЧТОБЫ НАЧАТЬ",
  stageClear: "Этап пройден",
  yourReward: "Твоя награда",
  youWon: "Ты выиграл. Эта деталь твоя. Ватты платят, чтобы поставить её в корпус.",
  practiceClear: "Тренировка пройдена. Настоящие доски в списке.",
  bits: "биты",
  star: "звезда",
  stars: "звезды",
  underPar: "Лучше пара",
  overPar: "Хуже пара",
  runAgain: "Ещё раз эта доска",
  backBoards: "Назад к доскам",
  learnPart: "Учить {part}",
  installPart: "Поставить {part}",
  saveOk: "Сохранено. В файле каждое короткое имя с этого компьютера.",
  saveNo: "Сохранение отменено.",
  paused: "Пауза",
  clockStopped: "Часы стоят.",
  boards: "Доски",
  unmute: "Звук",
  loading: "Доска грузится…",
  oneQuestion: "Один вопрос. Потом катишь.",
  goalKicker: "Помоги Берти",
  goalTitle: "Он учится, как устроен компьютер.",
  goalLine: "Ты помогаешь Берти. Выбери ПК.",
  goalGaming: "Игровой ПК",
  goalGamingLine: "Быстрые игры. Следи за GPU и теплом.",
  goalCreator: "ПК для творчества",
  goalCreatorLine: "Фото, музыка и видео. Следи за диском и GPU.",
  goalLaptop: "Ноутбук",
  goalLaptopLine: "Те же детали. Маленький, лёгкий и не горячий.",
  allPowers: "Все силы включены",
  turnsOn: "{name} включается сам.",
  zapStill: "Зап всё ещё кнопка.",
  yours: "Твоё",
  soon: "Дальше",
  powers: "Силы Берти",
  whatTheyDo: "Что они делают",
  allOn: "Все",
  win: "победа",
  wins: "победы",
  newOn: "Новое у Берти",
  onComputer: "{place} на этом компьютере",
  outHearts: "Сердца кончились",
  gameOver: "Конец игры",
  tryAgain: "Ещё раз",
  holes: "Ямы стоят сердце. Три промаха кончают забег.",
  early3d: "Лёгкие 3D доски возвращают тебя на путь. Дальше падение стоит сердце.",
  score: "Счёт",
  great: "Класс!",
  perfect: "Идеально!",
  continueQ: "Дальше?",
  newHigh: "Новый рекорд",
  ready: "Готов",
  go: "Вперёд",
  locked: "Закрыто",
  speaks: "Berty's Run говорит на твоём языке, от старта до результатов.",
  readSaid: "Чтение вслух включено.",
  courses: "Доски",
  alreadyOn: "+{n} ватт. ПК Берти уже включён.",
  nextReward: "+{n} ватт. Следующая награда: {part} ({cost}). У тебя {watts}.",
  everyWon: "Все детали выиграны. Поставь {part} за ватты.",
  bootPc: "+{n} ватт. Все детали внутри. Включи ПК.",
  cheer1: "Я поставил {name} на верхнюю полку. Ты первый.",
  cheer2: "Второй на {name}. Я слышу того, кто впереди.",
  cheer3: "Третий на {name}. Я написал твоё короткое имя на доске.",
  cheerN: "{place} на {name}. Назад это не сотрёт.",
  cheer0: "Я забрал биты с {name}. Звёзды останутся, если нажмёшь Назад.",
  watts: "ватт",
};

const AR: Screen = {
  ...EN,
  coin: "أدخل قطعة / المس للبدء",
  stageClear: "أنهيت المرحلة",
  yourReward: "جائزتك",
  youWon: "فزت. هذه القطعة لك. الواط تدفع لوضعها في الصندوق.",
  practiceClear: "انتهى التدريب. اللوحات الحقيقية في القائمة.",
  bits: "بتات",
  star: "نجمة",
  stars: "نجوم",
  underPar: "أفضل من الهدف",
  overPar: "أبطأ من الهدف",
  runAgain: "العب هذه اللوحة مرة أخرى",
  backBoards: "العودة إلى اللوحات",
  learnPart: "تعلّم {part}",
  installPart: "ركّب {part}",
  saveOk: "تم الحفظ. هذا الملف فيه كل اسم قصير على هذا الجهاز.",
  saveNo: "أُلغي الحفظ.",
  paused: "متوقف",
  clockStopped: "الساعة واقفة.",
  boards: "لوحات",
  unmute: "الصوت",
  loading: "تُحمَّل اللوحة…",
  oneQuestion: "سؤال واحد. ثم تتدحرج.",
  goalKicker: "ساعد بيرتي",
  goalTitle: "هو يتعلّم الحاسوب.",
  goalLine: "أنت تساعد بيرتي. اختر الحاسوب الذي تريده.",
  goalGaming: "حاسوب ألعاب",
  goalGamingLine: "ألعاب سريعة. راقب بطاقة الرسوم والحرارة.",
  goalCreator: "حاسوب إنشاء",
  goalCreatorLine: "صور وموسيقى وفيديو. راقب التخزين وبطاقة الرسوم.",
  goalLaptop: "حاسوب محمول",
  goalLaptopLine: "نفس القطع. صغير وخفيف وبارد بما يكفي.",
  allPowers: "كل القدرات تعمل",
  turnsOn: "{name} يعمل وحده.",
  zapStill: "زاب ما زال زرًا.",
  yours: "لك",
  soon: "التالي",
  powers: "قدرات بيرتي",
  whatTheyDo: "ماذا تفعل",
  allOn: "الكل",
  win: "فوز",
  wins: "انتصارات",
  newOn: "جديد عند بيرتي",
  onComputer: "{place} على هذا الجهاز",
  outHearts: "نفدت القلوب",
  gameOver: "انتهت اللعبة",
  tryAgain: "حاول مرة أخرى",
  holes: "الحفر تكلف قلبًا. ثلاث أخطاء تنهي الجولة.",
  early3d: "لوحات 3D السهلة تعيدك إلى الطريق. لاحقًا السقوط يكلف قلبًا.",
  score: "النقاط",
  great: "رائع!",
  perfect: "ممتاز!",
  continueQ: "نكمل؟",
  newHigh: "رقم جديد",
  ready: "استعد",
  go: "انطلق",
  locked: "مقفل",
  speaks: "بيرتي رن يتكلم لغتك، من البداية حتى النتائج.",
  readSaid: "القراءة بصوت عالٍ تعمل.",
  courses: "لوحات",
  alreadyOn: "+{n} واط. حاسوب بيرتي يعمل أصلًا.",
  nextReward: "+{n} واط. الجائزة التالية: {part} ({cost}). معك {watts}.",
  everyWon: "كل القطع رُبحت. ركّب {part} بالواط.",
  bootPc: "+{n} واط. كل القطع في الداخل. شغّل الحاسوب.",
  cheer1: "وضعت {name} على الرف الأعلى. أنت الأول.",
  cheer2: "الثاني في {name}. أسمع الذي أمامك.",
  cheer3: "الثالث في {name}. كتبت اسمك القصير على اللوحة.",
  cheerN: "{place} في {name}. الرجوع لا يمسحه.",
  cheer0: "حفظت البتات من {name}. نجومك تبقى إذا رجعت.",
  watts: "واط",
};

/* Dari, Kinyarwanda, and Tigrinya screen lines need a native check. See I18N-NOTES.md. */
const FA: Screen = {
  ...EN,
  coin: "سکه بینداز / برای شروع لمس کن",
  stageClear: "مرحله تمام شد",
  yourReward: "جایزه تو",
  youWon: "بردی. این پارچه از تو است. وات می‌پردازد تا در جعبه بنشیند.",
  practiceClear: "تمرین تمام شد. تخته‌های اصلی در فهرست است.",
  bits: "بیت",
  star: "ستاره",
  stars: "ستاره",
  underPar: "بهتر از هدف",
  overPar: "کندتر از هدف",
  runAgain: "این تخته را دوباره برو",
  backBoards: "بازگشت به تخته‌ها",
  learnPart: "یاد گرفتن {part}",
  installPart: "نصب {part}",
  saveOk: "ذخیره شد. این فایل هر نام کوتاه این کمپیوتر را دارد.",
  saveNo: "ذخیره لغو شد.",
  paused: "توقف",
  clockStopped: "ساعت ایستاده است.",
  boards: "تخته‌ها",
  unmute: "صدا",
  loading: "تخته بار می‌شود…",
  oneQuestion: "یک سوال. بعد می‌غلتی.",
  goalKicker: "به بیرتی کمک کن",
  goalTitle: "او کمپیوتر را یاد می‌گیرد.",
  goalLine: "تو به بیرتی کمک می‌کنی. کمپیوتری را که می‌خواهی انتخاب کن.",
  goalGaming: "کمپیوتر بازی",
  goalGamingLine: "بازی تیز. GPU و گرما را ببین.",
  goalCreator: "کمپیوتر ساختن",
  goalCreatorLine: "عکس، موسیقی و ویدیو. ذخیره و GPU را ببین.",
  goalLaptop: "لپ‌تاپ",
  goalLaptopLine: "همان پارچه‌ها. کوچک، سبک و به اندازه سرد.",
  allPowers: "همه قدرت‌ها روشن",
  turnsOn: "{name} خود به خود روشن می‌شود.",
  zapStill: "زاپ هنوز یک دکمه است.",
  yours: "از تو",
  soon: "بعدی",
  powers: "قدرت‌های بیرتی",
  whatTheyDo: "چه کار می‌کنند",
  allOn: "همه",
  win: "برد",
  wins: "بردها",
  newOn: "نو در بیرتی",
  onComputer: "{place} در این کمپیوتر",
  outHearts: "قلب تمام شد",
  gameOver: "بازی تمام شد",
  tryAgain: "دوباره کوشش کن",
  holes: "چُقوری یک قلب می‌گیرد. سه خطا دور را تمام می‌کند.",
  early3d: "تخته‌های آسان 3D تو را به راه برمی‌گرداند. بعد، افتادن یک قلب می‌گیرد.",
  score: "نمره",
  great: "آفرین!",
  perfect: "عالی!",
  continueQ: "ادامه؟",
  newHigh: "نمره نو",
  ready: "آماده",
  go: "برو",
  locked: "بسته",
  speaks: "بیرتی ران به زبان تو حرف می‌زند، از شروع تا نتیجه.",
  readSaid: "خواندن با صدا روشن است.",
  courses: "تخته‌ها",
  alreadyOn: "+{n} وات. کمپیوتر بیرتی از قبل روشن است.",
  nextReward: "+{n} وات. جایزه بعدی: {part} ({cost}). تو {watts} داری.",
  everyWon: "هر پارچه برده شده. {part} را با وات نصب کن.",
  bootPc: "+{n} وات. هر پارچه داخل است. کمپیوتر را روشن کن.",
  cheer1: "{name} را در طاق بالا گذاشتم. تو اول هستی.",
  cheer2: "دوم در {name}. کسی را که پیش روست می‌شنوم.",
  cheer3: "سوم در {name}. نام کوتاه تو را روی تخته نوشتم.",
  cheerN: "{place} در {name}. بازگشت آن را پاک نمی‌کند.",
  cheer0: "بیت‌های {name} را برداشتم. ستاره‌هایت می‌ماند اگر بازگردی.",
  watts: "وات",
};

const RW: Screen = {
  ...EN,
  coin: "SHYIRA IFARANGA / KANDA UTANGIRE",
  stageClear: "Warangije icyiciro",
  yourReward: "Igihembo cyawe",
  youWon: "Watsinze. Iki gice ni icyawe. Watts yishyura kugira kibone mu gasanduku.",
  practiceClear: "Imyitozo yarangiye. Imibaho y'ukuri iri ku rutonde.",
  bits: "bits",
  star: "inyenyeri",
  stars: "inyenyeri",
  underPar: "Munsi y'akaranganya",
  overPar: "Hejuru y'akaranganya",
  runAgain: "Ongera ukine iyi mbaho",
  backBoards: "Subira ku mbaho",
  learnPart: "Iga {part}",
  installPart: "Shyira {part}",
  saveOk: "Byabitswe. Iyi dosiye ifite buri zina rigufi kuri iyi mudasobwa.",
  saveNo: "Kubika byahagaritswe.",
  paused: "Hagarara",
  clockStopped: "Isaha yahagaze.",
  boards: "Imbaho",
  unmute: "Ijwi",
  loading: "Imbaho irapakira…",
  oneQuestion: "Ikibazo kimwe. Hanyuma ukizinga.",
  goalKicker: "Fasha Berty",
  goalTitle: "Ariga mudasobwa.",
  goalLine: "Ufasha Berty. Hitamo PC ushaka.",
  goalGaming: "PC y'imikino",
  goalGamingLine: "Imikino yihuta. Reba GPU n'ubushyuhe.",
  goalCreator: "PC yo kurema",
  goalCreatorLine: "Amafoto, umuziki, na videwo. Reba ububiko na GPU.",
  goalLaptop: "Mudasobwa nto",
  goalLaptopLine: "Ibice bimwe. Nto, yoroheje, kandi ikonje.",
  allPowers: "Imbaraga zose zirakora",
  turnsOn: "{name} iyaka ubwayo.",
  zapStill: "Zap ikibanza ari buto.",
  yours: "Iyawe",
  soon: "Ikikurikira",
  powers: "Imbaraga za Berty",
  whatTheyDo: "Icyo bikora",
  allOn: "Byose",
  win: "itsinzi",
  wins: "intsinzi",
  newOn: "Gishya kuri Berty",
  onComputer: "{place} kuri iyi mudasobwa",
  outHearts: "Umutima urashize",
  gameOver: "Umukino urarangiye",
  tryAgain: "Ongera ugerageze",
  holes: "Imyobo isaba umutima. Kutatsinda gatatu birangiza.",
  early3d: "Imbaho zoroshye za 3D zikugarura ku nzira. Nyuma, kugwa bisaba umutima.",
  score: "Amanota",
  great: "Byiza!",
  perfect: "Neza cyane!",
  continueQ: "Ukomeze?",
  newHigh: "Amanota mashya",
  ready: "Witegure",
  go: "Genda",
  locked: "Ifunze",
  speaks: "Berty's Run ivuga ururimi rwawe, kuva ku ntangiriro kugeza ku bisubizo.",
  readSaid: "Gusoma mu ijwi birakora.",
  courses: "Imbaho",
  alreadyOn: "+{n} watts. PC ya Berty imaze kwaka.",
  nextReward: "+{n} watts. Igihembo gikurikira: {part} ({cost}). Ufite {watts}.",
  everyWon: "Ibice byose byatsinzwe. Shyira {part} ukoresheje watts.",
  bootPc: "+{n} watts. Ibice byose biri imbere. Aka PC.",
  cheer1: "Nashyize {name} ku karato hejuru. Uri uwa mbere.",
  cheer2: "Uwa kabiri kuri {name}. Numva uri imbere yawe.",
  cheer3: "Uwa gatatu kuri {name}. Nanditse izina ryawe rigufi ku mbaho.",
  cheerN: "{place} kuri {name}. Gusubira inyuma ntibisiba.",
  cheer0: "Nafashe bits za {name}. Inyenyeri zawe ziguma niba usubira inyuma.",
  watts: "watts",
};

const TI: Screen = {
  ...EN,
  coin: "ሳንቲም ኣእቱ / ንምጅማር ጠውቕ",
  stageClear: "ደረጃ ተወዲኡ",
  yourReward: "ሽልማትካ",
  youWon: "ተዓዊትካ። እዚ ክፋል ናትካ እዩ። ዋት ንኽኣቱ ኣብ ሳንዱቕ ይከፍል።",
  practiceClear: "ልምምድ ተወዲኡ። ሓቀኛ ቦርድታት ኣብ ዝርዝር እዮም።",
  bits: "ቢት",
  star: "ኮኾብ",
  stars: "ኮኾባት",
  underPar: "ካብ ዕላማ ዝሓሸ",
  overPar: "ካብ ዕላማ ዝደንጎየ",
  runAgain: "ነዚ ቦርድ ደጊምካ ውሰድ",
  backBoards: "ናብ ቦርድታት ተመለስ",
  learnPart: "ተማሃር {part}",
  installPart: "ጽዓን {part}",
  saveOk: "ተዓቂቡ። እዚ ፋይል ነፍሲ ወከፍ ሓጺር ስም ናይዚ ኮምፒተር ኣለዎ።",
  saveNo: "ምዕቃብ ተሰሪዙ።",
  paused: "ጠጠው",
  clockStopped: "ሰዓት ደው ኣሉ።",
  boards: "ቦርድታት",
  unmute: "ድምጺ",
  loading: "ቦርድ ይጽዕን ኣሎ…",
  oneQuestion: "ሓደ ሕቶ። ድሕሪኡ ትንከባለል።",
  goalKicker: "ንበርቲ ሓግዝ",
  goalTitle: "ኮምፒተር ይመሃር ኣሎ።",
  goalLine: "ንበርቲ ትሕግዝ። ዝደሊኻዮ PC ምረጽ።",
  goalGaming: "ናይ ጸወታ PC",
  goalGamingLine: "ቅልጡፍ ጸወታ። GPUን ሙቐትን ርአ።",
  goalCreator: "ናይ ምፍጣር PC",
  goalCreatorLine: "ስእሊ፣ ሙዚቃ፣ ቪድዮ። መኽዘንን GPUን ርአ።",
  goalLaptop: "ላፕቶፕ",
  goalLaptopLine: "ተመሳሳሊ ክፋላት። ነኣሽቱ፣ ቀሊል፣ ንኽትሕዞ ዝኸኣለ ዝሑል።",
  allPowers: "ኩሉ ሓይሊ ተወሊዑ",
  turnsOn: "{name} ባዕሉ ይበራሕ።",
  zapStill: "ዛፕ ገና መጠወቒ እዩ።",
  yours: "ናትካ",
  soon: "ዝቕጽል",
  powers: "ሓይልታት በርቲ",
  whatTheyDo: "እንታይ ይገብሩ",
  allOn: "ኩሉ",
  win: "ዓወት",
  wins: "ዓወታት",
  newOn: "ሓድሽ ኣብ በርቲ",
  onComputer: "{place} ኣብዚ ኮምፒተር",
  outHearts: "ልቢ ተወዲኡ",
  gameOver: "ጸወታ ተወዲኡ",
  tryAgain: "ደጊምካ ፈትን",
  holes: "ጉድጓድ ሓደ ልቢ ይወስድ። ሰለስተ ስሕተት ነቲ ዙር ይውድእ።",
  early3d: "ቀለልቲ 3D ቦርድታት ናብ መንገዲ የምልሱኻ። ድሕሪኡ ምውዳቕ ሓደ ልቢ ይወስድ።",
  score: "ነጥቢ",
  great: "ጽቡቕ!",
  perfect: "ፍጹም!",
  continueQ: "ትቅጽል?",
  newHigh: "ሓድሽ ሪከርድ",
  ready: "ተዳለ",
  go: "ኪድ",
  locked: "ተዓጽዩ",
  speaks: "በርቲ ራን ብቋንቋኻ ይዛረብ፣ ካብ ጅማሬ ክሳብ ውጽኢት።",
  readSaid: "ድምጺ ምንባብ ተወሊዑ።",
  courses: "ቦርድታት",
  alreadyOn: "+{n} ዋት። PC ናይ በርቲ ድሮ ተወሊዑ።",
  nextReward: "+{n} ዋት። ዝቕጽል ሽልማት: {part} ({cost})። {watts} ኣለካ።",
  everyWon: "ኩሉ ክፋል ተረኺቡ። {part} ብዋት ጽዓን።",
  bootPc: "+{n} ዋት። ኩሉ ክፋል ኣብ ውሽጢ እዩ። PC ኣብርህ።",
  cheer1: "{name} ኣብ ላዕለዋይ መደርደሪ ጌረዮ። ንስኻ ቀዳማይ ኢኻ።",
  cheer2: "ካልኣይ ኣብ {name}። ነቲ ኣብ ቅድሚኻ ዘሎ እሰምዕ።",
  cheer3: "ሳልሳይ ኣብ {name}። ሓጺር ስምካ ኣብ ቦርድ ጽሒፈዮ።",
  cheerN: "{place} ኣብ {name}። ምምላስ ኣይድምስሶን።",
  cheer0: "ቢት ካብ {name} ወሲደ። ኮኾብካ ይቕመጥ እንተ ተመሊስካ።",
  watts: "ዋት",
};

const SCREENS: Record<Lang, Screen> = {
  en: EN,
  simple: SIMPLE,
  es: ES,
  uk: UK,
  ru: RU,
  ar: AR,
  "fa-AF": FA,
  rw: RW,
  ti: TI,
};

type Drive = { name: string; line: string };
type Sticker = { name: string; line: string };

function drives(rows: Record<DriveId, Drive>) {
  return rows;
}

const EXTRA: Partial<Record<Lang, Record<string, unknown>>> = {
  uk: {
    readOn: "Так",
    readOff: "Ні",
    big: "Великі літери",
    fewer: "Менше відповідей",
    tools: "Ще тут",
    learn: "Вчитись",
    how: "Як грати",
    soundOff: "Без звуку",
    save: "Зберегти перемоги",
    lab: "Збери ПК",
    goal: "Змінити ПК",
    paper: "Паперовий план",
    file: "Відкрити файл",
    readBtn: "Читати",
    try: "Спробуй іншу відповідь.",
    go: "Перевір цю деталь",
    playStyle: "Як керувати",
    heat: "Змагання",
    onePlayer: "Один гравець",
    twoPlayers: "Два гравці",
    hideScores: "Сховати бали",
    bestOn: "Кращий забіг увімкнено",
    bestOff: "Кращий забіг вимкнено",
    thisHour: "Ця година",
    teacherPin: "Код учителя",
    teacherOn: "Код учителя ввімкнено",
    open: "Відкрити",
    wrongPin: "Хибний код",
    signedIn: "Вхід є. Бали йдуть за кодом TechWorks.",
    signedOut: "Входу немає. Грати можна. Бали лишаються на цьому пристрої.",
    menu: "Меню",
    mute: "Тиша",
    fullScreen: "На весь екран",
    cabinet: "Автомат",
    arcade: "Аркада",
    classic: "Тихий",
    cabinetHelp: "Тихий вигляд спокійний. Аркада — це автомат.",
    scanlines: "Смуги",
    offMotion: "Вимкнено, якщо є рух",
    skin: "Колір Берті",
    sticker: "Наліпка",
    rig: "Твій набір",
    paint: "Лише фарба. Деталі все одно з дошок.",
    wins: "перемог",
    drives: drives({
      lean: { name: "Нахил", line: "Один стік або WASD." },
      hands: { name: "Дві руки", line: "Два пальці на телефоні." },
      keys: { name: "Клавіші і миша", line: "2D: миша. 3D: WASD і миша." },
      follow: { name: "За пальцем", line: "Постав палець, куди Берті має котитись." },
      tilt: { name: "Нахили пристрій", line: "Нахили планшет. Багато Chromebook без датчика." },
    }),
    cabs: { neon: "Неон", sunset: "Захід", mint: "М'ята", mono: "Зелений" },
    skins: { lime: "Лайм", cyan: "Блакить", magenta: "Маджента", gold: "Золото", rainbow: "Веселка" },
    stickers: {
      bolt: { name: "Блискавка", line: "Живлення" },
      star: { name: "Біт", line: "Біт, який ти спіймав" },
      chip: { name: "Чип", line: "Мозок" },
      heart: { name: "Вентилятор", line: "Тримає холод" },
    } satisfies Record<string, Sticker>,
  },
  ru: {
    readOn: "Да",
    readOff: "Нет",
    big: "Крупные буквы",
    fewer: "Меньше ответов",
    tools: "Ещё здесь",
    learn: "Учиться",
    how: "Как играть",
    soundOff: "Без звука",
    save: "Сохранить победы",
    lab: "Собери ПК",
    goal: "Сменить ПК",
    paper: "Бумажный план",
    file: "Открыть файл",
    readBtn: "Читать",
    try: "Попробуй другой ответ.",
    go: "Проверь эту деталь",
    playStyle: "Как рулить",
    heat: "Соревнование",
    onePlayer: "Один игрок",
    twoPlayers: "Два игрока",
    hideScores: "Скрыть баллы",
    bestOn: "Лучший забег включён",
    bestOff: "Лучший забег выключен",
    thisHour: "Этот час",
    teacherPin: "Код учителя",
    teacherOn: "Код учителя включён",
    open: "Открыть",
    wrongPin: "Неверный код",
    signedIn: "Вход есть. Баллы идут по коду TechWorks.",
    signedOut: "Входа нет. Играть можно. Баллы остаются на этом устройстве.",
    menu: "Меню",
    mute: "Тихо",
    fullScreen: "На весь экран",
    cabinet: "Автомат",
    arcade: "Аркада",
    classic: "Тихий",
    cabinetHelp: "Тихий вид спокойный. Аркада — это автомат.",
    scanlines: "Полосы",
    offMotion: "Выключено, если есть движение",
    skin: "Цвет Берти",
    sticker: "Наклейка",
    rig: "Твой набор",
    paint: "Только краска. Детали всё равно с досок.",
    wins: "побед",
    drives: drives({
      lean: { name: "Наклон", line: "Один стик или WASD." },
      hands: { name: "Две руки", line: "Два пальца на телефоне." },
      keys: { name: "Клавиши и мышь", line: "2D: мышь. 3D: WASD и мышь." },
      follow: { name: "За пальцем", line: "Поставь палец, куда Берти должен катиться." },
      tilt: { name: "Наклони устройство", line: "Наклони планшет. У многих Chromebook нет датчика." },
    }),
    cabs: { neon: "Неон", sunset: "Закат", mint: "Мята", mono: "Зелёный" },
    skins: { lime: "Лайм", cyan: "Голубой", magenta: "Маджента", gold: "Золото", rainbow: "Радуга" },
    stickers: {
      bolt: { name: "Молния", line: "Питание" },
      star: { name: "Бит", line: "Бит, который ты поймал" },
      chip: { name: "Чип", line: "Мозг" },
      heart: { name: "Вентилятор", line: "Держит холод" },
    },
  },
  ar: {
    readOn: "نعم",
    readOff: "لا",
    big: "حروف كبيرة",
    fewer: "إجابات أقل",
    tools: "هنا أيضًا",
    learn: "تعلّم",
    how: "كيف تلعب",
    soundOff: "بلا صوت",
    save: "احفظ الفوز",
    lab: "ابنِ الحاسوب",
    goal: "غيّر الحاسوب",
    paper: "خطة ورق",
    file: "افتح ملفًا محفوظًا",
    readBtn: "اقرأ",
    try: "جرّب جوابًا آخر.",
    go: "اختبر هذه القطعة",
    playStyle: "طريقة اللعب",
    heat: "منافسة",
    onePlayer: "لاعب واحد",
    twoPlayers: "لاعبان",
    hideScores: "أخفِ النقاط",
    bestOn: "أفضل جولة تعمل",
    bestOff: "أفضل جولة متوقفة",
    thisHour: "هذه الحصة",
    teacherPin: "رمز المعلّم",
    teacherOn: "رمز المعلّم يعمل",
    open: "افتح",
    wrongPin: "رمز خطأ",
    signedIn: "أنت داخل. النقاط تستعمل رمز TechWorks.",
    signedOut: "لست داخلًا. يمكنك اللعب. النقاط تبقى على هذا الجهاز.",
    menu: "القائمة",
    mute: "كتم",
    fullScreen: "ملء الشاشة",
    cabinet: "الخزانة",
    arcade: "ألعاب",
    classic: "هادئ",
    cabinetHelp: "الهادئ مظهر هادئ. الألعاب هي الخزانة.",
    scanlines: "خطوط",
    offMotion: "متوقف عند الحركة",
    skin: "لون بيرتي",
    sticker: "ملصق",
    rig: "جهازك",
    paint: "لون فقط. القطع ما زالت تأتي من اللوحات.",
    wins: "انتصارات",
    drives: drives({
      lean: { name: "ميل", line: "عصا واحدة، أو WASD." },
      hands: { name: "يدان", line: "إبهامان على الهاتف." },
      keys: { name: "مفاتيح وفأرة", line: "2D: الفأرة. 3D: WASD والفأرة." },
      follow: { name: "اتبع", line: "ضع إصبعًا حيث يجب أن يتدحرج بيرتي." },
      tilt: { name: "أمل الجهاز", line: "أمل الجهاز اللوحي. كثير من أجهزة Chromebook بلا حسّاس." },
    }),
    cabs: { neon: "نيون", sunset: "غروب", mint: "نعناع", mono: "أخضر" },
    skins: { lime: "ليموني", cyan: "سماوي", magenta: "وردي", gold: "ذهبي", rainbow: "قوس قزح" },
    stickers: {
      bolt: { name: "برق", line: "طاقة" },
      star: { name: "بت", line: "بت التقطته" },
      chip: { name: "شريحة", line: "العقل" },
      heart: { name: "مروحة", line: "يبقيه باردًا" },
    },
  },
  "fa-AF": {
    readOn: "بلی",
    readOff: "نخیر",
    big: "حرف بزرگ",
    fewer: "جواب کمتر",
    tools: "اینجا هم",
    learn: "یاد گرفتن",
    how: "چطور بازی شود",
    soundOff: "بی‌صدا",
    save: "بردها را ذخیره کن",
    lab: "کمپیوتر را بساز",
    goal: "کمپیوتر را عوض کن",
    paper: "پلان کاغذ",
    file: "یک فایل ذخیره را باز کن",
    readBtn: "بخوان",
    try: "جواب دیگر را ببین.",
    go: "این پارچه را امتحان کن",
    playStyle: "طرز بازی",
    heat: "مسابقه",
    onePlayer: "یک بازیکن",
    twoPlayers: "دو بازیکن",
    hideScores: "نمره‌ها را پنهان کن",
    bestOn: "بهترین دور روشن",
    bestOff: "بهترین دور خاموش",
    thisHour: "این ساعت",
    teacherPin: "پین معلم",
    teacherOn: "پین معلم روشن است",
    open: "باز کن",
    wrongPin: "پین غلط",
    signedIn: "داخل شدی. نمره‌ها از کود TechWorks کار می‌گیرد.",
    signedOut: "داخل نشدی. بازی کرده می‌توانی. نمره‌ها در این دستگاه می‌ماند.",
    menu: "منو",
    mute: "خاموشی صدا",
    fullScreen: "تمام صفحه",
    cabinet: "کابینت",
    arcade: "بازی‌خانه",
    classic: "آرام",
    cabinetHelp: "آرام نگاه خاموش است. بازی‌خانه همان کابینت است.",
    scanlines: "خط‌ها",
    offMotion: "اگر حرکت باشد خاموش",
    skin: "رنگ بیرتی",
    sticker: "برچسب",
    rig: "دستگاه تو",
    paint: "فقط رنگ. پارچه‌ها باز از تخته‌ها می‌آیند.",
    wins: "برد",
    drives: drives({
      lean: { name: "میل", line: "یک استک، یا WASD." },
      hands: { name: "دو دست", line: "دو انگشت روی تلیفون." },
      keys: { name: "کلید و موس", line: "2D: موس. 3D: WASD و موس." },
      follow: { name: "دنبال", line: "انگشت را جایی بگذار که بیرتی بغلد." },
      tilt: { name: "کج کردن", line: "تبلت را کج کن. بسیاری Chromebook سنسور ندارند." },
    }),
    cabs: { neon: "نیون", sunset: "غروب", mint: "نعناع", mono: "سبز" },
    skins: { lime: "لیمویی", cyan: "آبی", magenta: "گلابی", gold: "طلایی", rainbow: "رنگین‌کمان" },
    stickers: {
      bolt: { name: "برق", line: "انرژی" },
      star: { name: "بیت", line: "بیتی که گرفتی" },
      chip: { name: "چیپ", line: "مغز" },
      heart: { name: "پکه", line: "سرد نگه می‌دارد" },
    },
  },
  rw: {
    readOn: "Yego",
    readOff: "Oya",
    big: "Inyuguti nini",
    fewer: "Ibisubizo bike",
    tools: "Nanone hano",
    learn: "Iga",
    how: "Uko ukina",
    soundOff: "Nta jwi",
    save: "Bika intsinzi",
    lab: "Ubake PC",
    goal: "Hindura PC",
    paper: "Gahunda y'urupapuro",
    file: "Fungura dosiye",
    readBtn: "Soma",
    try: "Gerageza ikindi gisubizo.",
    go: "Gerageza iki gice",
    playStyle: "Uko uyobora",
    heat: "Amarushanwa",
    onePlayer: "Umukinnyi umwe",
    twoPlayers: "Abakinnyi babiri",
    hideScores: "Hisha amanota",
    bestOn: "Ikizamini cyiza kirakora",
    bestOff: "Ikizamini cyiza kirahagarara",
    thisHour: "Iyi saha",
    teacherPin: "Kode y'umwarimu",
    teacherOn: "Kode y'umwarimu irakora",
    open: "Fungura",
    wrongPin: "Kode itari yo",
    signedIn: "Winjiye. Amanota akoresha kode ya TechWorks.",
    signedOut: "Ntabwo winjiye. Ushobora gukina. Amanota aguma kuri iki gikoresho.",
    menu: "Ibikubiyemo",
    mute: "Gatuza",
    fullScreen: "Mugaragaza yuzuye",
    cabinet: "Akabati",
    arcade: "Arcade",
    classic: "Ituje",
    cabinetHelp: "Ituje ni isura ituje. Arcade ni akabati.",
    scanlines: "Imirongo",
    offMotion: "Izimye iyo harimo kugenda",
    skin: "Ibara rya Berty",
    sticker: "Agafoto gato",
    rig: "Igikoresho cyawe",
    paint: "Ibara gusa. Ibice bikiboneka mu mbaho.",
    wins: "intsinzi",
    drives: drives({
      lean: { name: "Kegama", line: "Inkoni imwe, cyangwa WASD." },
      hands: { name: "Amaboko abiri", line: "Intoki ebyiri ku telefoni." },
      keys: { name: "Utubuto n'imbeba", line: "2D: imbeba. 3D: WASD n'imbeba." },
      follow: { name: "Kurikira", line: "Shyira urutoki aho Berty agomba kuzinga." },
      tilt: { name: "Kegama igikoresho", line: "Kegama tableti. Chromebook nyinshi ntizifite senseri." },
    }),
    cabs: { neon: "Neon", sunset: "Izuba rirenga", mint: "Menthe", mono: "Icyatsi" },
    skins: { lime: "Lime", cyan: "Cyan", magenta: "Magenta", gold: "Zahabu", rainbow: "Umutiganda" },
    stickers: {
      bolt: { name: "Umurabyo", line: "Imbaraga" },
      star: { name: "Bit", line: "Bit wafashe" },
      chip: { name: "Chip", line: "Ubwenge" },
      heart: { name: "Umuyaga", line: "Bikomeza bikonje" },
    },
  },
  ti: {
    readOn: "እወ",
    readOff: "ኣይኮነን",
    big: "ዓበይቲ ፊደላት",
    fewer: "ውሑዳት መልስታት",
    tools: "ኣብዚ እውን",
    learn: "ተማሃር",
    how: "ከመይ ትጻወት",
    soundOff: "ብዘይ ድምጺ",
    save: "ዓወታት ዕቀብ",
    lab: "PC ሰሪሕ",
    goal: "PC ቀይር",
    paper: "ናይ ወረቐት ውጥን",
    file: "ዝተዓቐበ ፋይል ክፈት",
    readBtn: "ንበብ",
    try: "ካልእ መልሲ ፈትን።",
    go: "ነዚ ክፋል ፈትን",
    playStyle: "ኣገባብ ጸወታ",
    heat: "ውድድር",
    onePlayer: "ሓደ ተጻዋቲ",
    twoPlayers: "ክልተ ተጻወቲ",
    hideScores: "ነጥብታት ሕባእ",
    bestOn: "ዝበለጸ ዙር ተወሊዑ",
    bestOff: "ዝበለጸ ዙር ጠፊኡ",
    thisHour: "እዚ ሰዓት",
    teacherPin: "መፍትሕ መምህር",
    teacherOn: "መፍትሕ መምህር ተወሊዑ",
    open: "ክፈት",
    wrongPin: "ጌጋ መፍትሕ",
    signedIn: "ኣቲኻ ኣለኻ። ነጥቢ ናይ TechWorks ኮድ ይጥቀም።",
    signedOut: "ኣይኣተኻን። ክትጻወት ትኽእል። ነጥቢ ኣብዚ መሳርሒ ይቕመጥ።",
    menu: "ዝርዝር",
    mute: "ስቕታ",
    fullScreen: "ምሉእ ስክሪን",
    cabinet: "ካቢኔ",
    arcade: "መጻወቲ",
    classic: "ጽምው",
    cabinetHelp: "ጽምው ጽምው መልክዕ እዩ። መጻወቲ እቲ ካቢኔ እዩ።",
    scanlines: "መስመራት",
    offMotion: "ምንቅስቓስ እንተሎ ይጥፋእ",
    skin: "ሕብሪ በርቲ",
    sticker: "ስቲከር",
    rig: "መሳርሒኻ",
    paint: "ቀለም ጥራይ። ክፋላት ካብ ቦርድ ይመጹ።",
    wins: "ዓወታት",
    drives: drives({
      lean: { name: "ኣንክላ", line: "ሓደ ስቲክ፣ ወይ WASD." },
      hands: { name: "ክልተ ኢድ", line: "ክልተ ኣጻብዕቲ ኣብ ተሌፎን።" },
      keys: { name: "ቁልፊን ማውስን", line: "2D: ማውስ። 3D: WASDን ማውስን።" },
      follow: { name: "ስዓብ", line: "ኣጻብዕ ኣብ ዝከይድ ቦታ በርቲ ኣቐምጥ።" },
      tilt: { name: "ኣንክል", line: "ታብሌት ኣንክል። ብዙሕ Chromebook ሴንሰር የብሉን።" },
    }),
    cabs: { neon: "ኒዮን", sunset: "ዕራርቦ", mint: "ሚንት", mono: "ቆጽለ" },
    skins: { lime: "ላይም", cyan: "ሰማያዊ", magenta: "ሮዛ", gold: "ወርቂ", rainbow: "ቀስተ ደመና" },
    stickers: {
      bolt: { name: "በርቂ", line: "ሓይሊ" },
      star: { name: "ቢት", line: "ዝሓዝካዮ ቢት" },
      chip: { name: "ቺፕ", line: "እንጎል" },
      heart: { name: "ፋን", line: "ዝሑል ይገብሮ" },
    },
  },
};

function core(lang: Lang): Ui {
  if (lang === "en" || lang === "simple" || lang === "es") return ACCESS_UI[lang] as unknown as Ui;
  const extra = EXTRA[lang] ?? {};
  const en = ACCESS_UI.en;
  return {
    ...en,
    ...extra,
    drives: { ...en.drives, ...(extra.drives as object) },
    cabs: { ...en.cabs, ...(extra.cabs as object) },
    skins: { ...en.skins, ...(extra.skins as object) },
    stickers: { ...en.stickers, ...(extra.stickers as object) },
  } as unknown as Ui;
}

export type Face = Ui & Screen & {
  playWord: string;
  levelsWord: string;
  nextWord: string;
  helpWord: string;
  whatsNew: string;
  closeWord: string;
  noVoice: string;
};

export function screen(lang: Lang): Screen {
  return SCREENS[lang] ?? EN;
}

export function face(lang: Lang): Face {
  const ui = { ...core(lang), ...screen(lang) } as Face;
  const put = (key: keyof Ui, sharedKey: string) => {
    const v = shared(sharedKey);
    if (v) (ui as unknown as Record<string, string>)[key as string] = v;
  };
  put("settings", "settings");
  put("language", "language");
  put("sound", "sound");
  put("home", "home");
  put("back", "back");
  put("signIn", "signIn");
  put("scores", "scores");
  put("pause", "pause");
  put("resume", "resume");
  put("retry", "retry");
  put("exit", "exit");
  put("music", "music");
  put("volume", "volume");
  const read = shared("readAloud");
  const bag = ui as unknown as Record<string, string>;
  if (read) bag.read = read;
  ui.playWord = shared("play") || "Play";
  ui.levelsWord = shared("levels") || "Levels";
  ui.nextWord = shared("next") || "Next";
  ui.helpWord = shared("help") || "Help";
  ui.whatsNew = shared("whatsNew") || "What's new";
  ui.closeWord = shared("close") || "Close";
  ui.noVoice = shared("noVoice") || "No voice yet. Read the words.";
  const menu = shared("menu");
  if (menu && (lang === "en" || lang === "simple" || menu !== "Menu")) bag.menu = menu;
  return ui;
}

const COURSE_EN: Record<string, string> = {
  "practice-2d": "Practice 2D",
  "practice-3d": "Practice 3D",
  "tube-run": "Bus Tube",
  "roll-out": "Roll Out",
  "mind-the-pit": "Mind the Pit",
  "saw-line": "Fan Line",
  "oil-pan": "Thermal Paste",
  "crew-gate": "Crew Gate",
  "around-the-bend": "Around the Bend",
  "pit-drop": "Pit Drop",
  "blade-walk": "Blade Walk",
  "slick-shelf": "Slick Shelf",
  "shop-exit": "I/O Exit",
  "cable-loom": "Cable Loom",
  "case-fan": "Case Fan",
  "heat-sink": "Heat Sink",
  "packet-lane": "Packet Lane",
  "signal-hop": "Signal Hop",
  "case-drop": "Case Drop",
  "dark-bay": "Dark Bay",
};

const COURSE: Partial<Record<Lang, Record<string, string>>> = {
  simple: { ...COURSE_EN, "practice-2d": "Practice flat", "practice-3d": "Practice deep", "tube-run": "Bus tube" },
  es: {
    "practice-2d": "Práctica 2D",
    "practice-3d": "Práctica 3D",
    "tube-run": "Tubo bus",
    "roll-out": "Salida",
    "mind-the-pit": "Cuidado con el hueco",
    "saw-line": "Línea de ventilador",
    "oil-pan": "Pasta térmica",
    "crew-gate": "Puerta de equipo",
    "around-the-bend": "En la curva",
    "pit-drop": "Caída",
    "blade-walk": "Paso de aspas",
    "slick-shelf": "Estante liso",
    "shop-exit": "Salida E/S",
    "cable-loom": "Cables",
    "case-fan": "Ventilador",
    "heat-sink": "Disipador",
    "packet-lane": "Carril de paquetes",
    "signal-hop": "Salto de señal",
    "case-drop": "Caja",
    "dark-bay": "Bahía oscura",
  },
  uk: {
    "practice-2d": "Тренування 2D",
    "practice-3d": "Тренування 3D",
    "tube-run": "Шина-труба",
    "roll-out": "Викат",
    "mind-the-pit": "Стережись ями",
    "saw-line": "Лінія вентилятора",
    "oil-pan": "Термопаста",
    "crew-gate": "Брама команди",
    "around-the-bend": "За поворотом",
    "pit-drop": "Падіння",
    "blade-walk": "Між лопатями",
    "slick-shelf": "Слизька полиця",
    "shop-exit": "Вихід В/В",
    "cable-loom": "Джгут",
    "case-fan": "Вентилятор",
    "heat-sink": "Радіатор",
    "packet-lane": "Доріжка пакетів",
    "signal-hop": "Стрибок сигналу",
    "case-drop": "Корпус",
    "dark-bay": "Темна ніша",
  },
  ru: {
    "practice-2d": "Тренировка 2D",
    "practice-3d": "Тренировка 3D",
    "tube-run": "Шина-труба",
    "roll-out": "Выкат",
    "mind-the-pit": "Берегись ямы",
    "saw-line": "Линия вентилятора",
    "oil-pan": "Термопаста",
    "crew-gate": "Ворота команды",
    "around-the-bend": "За поворотом",
    "pit-drop": "Падение",
    "blade-walk": "Между лопастями",
    "slick-shelf": "Скользкая полка",
    "shop-exit": "Выход В/В",
    "cable-loom": "Жгут",
    "case-fan": "Вентилятор",
    "heat-sink": "Радиатор",
    "packet-lane": "Дорожка пакетов",
    "signal-hop": "Прыжок сигнала",
    "case-drop": "Корпус",
    "dark-bay": "Тёмная ниша",
  },
  ar: {
    "practice-2d": "تدريب 2D",
    "practice-3d": "تدريب 3D",
    "tube-run": "أنبوب الناقل",
    "roll-out": "انطلاق",
    "mind-the-pit": "احذر الحفرة",
    "saw-line": "خط المروحة",
    "oil-pan": "معجون حراري",
    "crew-gate": "بوابة الفريق",
    "around-the-bend": "عند المنعطف",
    "pit-drop": "سقوط",
    "blade-walk": "بين الريش",
    "slick-shelf": "رف زلق",
    "shop-exit": "مخرج إدخال",
    "cable-loom": "حزمة كيبل",
    "case-fan": "مروحة الصندوق",
    "heat-sink": "مشتت",
    "packet-lane": "ممر الحزم",
    "signal-hop": "قفزة إشارة",
    "case-drop": "الصندوق",
    "dark-bay": "خليج مظلم",
  },
  "fa-AF": {
    "practice-2d": "تمرین 2D",
    "practice-3d": "تمرین 3D",
    "tube-run": "لوله بس",
    "roll-out": "بیرون شدن",
    "mind-the-pit": "از چقوری بپرهیز",
    "saw-line": "خط پکه",
    "oil-pan": "خمیر گرما",
    "crew-gate": "دروازه گروه",
    "around-the-bend": "سر پیچ",
    "pit-drop": "افتادن",
    "blade-walk": "میان پر",
    "slick-shelf": "تاق لغزنده",
    "shop-exit": "خروج ورودی",
    "cable-loom": "دسته کیبل",
    "case-fan": "پکه جعبه",
    "heat-sink": "سردکننده",
    "packet-lane": "راه بسته",
    "signal-hop": "پریدن سیگنال",
    "case-drop": "جعبه",
    "dark-bay": "خلیج تاریک",
  },
  rw: {
    "practice-2d": "Imyitozo 2D",
    "practice-3d": "Imyitozo 3D",
    "tube-run": "Umuhora",
    "roll-out": "Gusohoka",
    "mind-the-pit": "Menya umwobo",
    "saw-line": "Umurongo w'umuyaga",
    "oil-pan": "Umutobe w'ubushyuhe",
    "crew-gate": "Irembo ry'ikipe",
    "around-the-bend": "Ku mpambuko",
    "pit-drop": "Kugwa",
    "blade-walk": "Hagati y'amapapa",
    "slick-shelf": "Ikarato ritera",
    "shop-exit": "Igisohoka",
    "cable-loom": "Imigozi",
    "case-fan": "Umuyaga",
    "heat-sink": "Igikonjesha",
    "packet-lane": "Inzira ya paki",
    "signal-hop": "Gusimbuka kw'ikimenyetso",
    "case-drop": "Agasanduku",
    "dark-bay": "Ahantu h'Umwijima",
  },
  ti: {
    "practice-2d": "ልምምድ 2D",
    "practice-3d": "ልምምድ 3D",
    "tube-run": "ቱቦ ባስ",
    "roll-out": "ምውጻእ",
    "mind-the-pit": "ጉድጓድ ተጠንቀቕ",
    "saw-line": "መስመር ፋን",
    "oil-pan": "ለቕለቕ ሙቐት",
    "crew-gate": "ማዕጾ ጉጅለ",
    "around-the-bend": "ኣብ መጥምዚ",
    "pit-drop": "ምውዳቕ",
    "blade-walk": "ኣብ መንጎ ክንፊ",
    "slick-shelf": "መደርደሪ ዝንሽር",
    "shop-exit": "መውጻኢ",
    "cable-loom": "ገመድ",
    "case-fan": "ፋን ሳንዱቕ",
    "heat-sink": "መዝሓሊ",
    "packet-lane": "መንገዲ ጥቕሊ",
    "signal-hop": "ዝላ ምልክት",
    "case-drop": "ሳንዱቕ",
    "dark-bay": "ጸልማት ወደብ",
  },
};

export function courseLabel(lang: Lang, id: string, fallback: string): string {
  return COURSE[lang]?.[id] || (lang === "simple" ? COURSE.simple?.[id] : "") || COURSE_EN[id] || fallback;
}

const PART: Partial<Record<Lang, Record<string, string>>> = {
  es: { mobo: "Placa base", psu: "Fuente", cpu: "CPU", ram: "RAM", fan: "Ventilador", ssd: "SSD", gpu: "GPU", nic: "Tarjeta de red", os: "BertyOS" },
  uk: { mobo: "Плата", psu: "Блок живлення", cpu: "CPU", ram: "RAM", fan: "Охолодження", ssd: "SSD", gpu: "GPU", nic: "Мережева карта", os: "BertyOS" },
  ru: { mobo: "Плата", psu: "Блок питания", cpu: "CPU", ram: "RAM", fan: "Охлаждение", ssd: "SSD", gpu: "GPU", nic: "Сетевая карта", os: "BertyOS" },
  ar: { mobo: "اللوحة الأم", psu: "مزود الطاقة", cpu: "CPU", ram: "RAM", fan: "المبرّد", ssd: "SSD", gpu: "GPU", nic: "بطاقة الشبكة", os: "BertyOS" },
  "fa-AF": { mobo: "برد مادر", psu: "منبع برق", cpu: "CPU", ram: "RAM", fan: "سردکننده", ssd: "SSD", gpu: "GPU", nic: "کارت شبکه", os: "BertyOS" },
  rw: { mobo: "Ikibaho", psu: "Imbaraga", cpu: "CPU", ram: "RAM", fan: "Igikonjesha", ssd: "SSD", gpu: "GPU", nic: "Ikarita y'urusobe", os: "BertyOS" },
  ti: { mobo: "ማዘርቦርድ", psu: "መብራህቲ", cpu: "CPU", ram: "RAM", fan: "መዝሓሊ", ssd: "SSD", gpu: "GPU", nic: "ካርድ መርበብ", os: "BertyOS" },
};

const PART_EN: Record<string, string> = {
  mobo: "Motherboard",
  psu: "Power supply",
  cpu: "CPU",
  ram: "RAM",
  fan: "Cooler",
  ssd: "SSD",
  gpu: "GPU",
  nic: "Network card",
  os: "BertyOS",
};

export function partLabel(lang: Lang, id: string, fallback: string): string {
  return PART[lang]?.[id] || PART_EN[id] || fallback;
}

export function rewardLine(lang: Lang, earned: number, watts: number, parts: string[], booted: boolean, bests: Record<string, number>): string {
  const s = screen(lang);
  const fill = (t: string, extra: Record<string, string> = {}) =>
    t.replace("{n}", String(earned)).replace("{watts}", String(watts)).replace(/\{(\w+)\}/g, (_, k) => extra[k] ?? "");
  if (booted) return fill(s.alreadyOn);
  const pending = PARTS.find((part) => {
    const board = courseForPart(part.id);
    return !!board && bests[board.id] == null;
  });
  if (pending) return fill(s.nextReward, { part: partLabel(lang, pending.id, pending.name), cost: String(pending.cost) });
  const uninstalled = nextPart(parts);
  if (uninstalled) return fill(s.everyWon, { part: partLabel(lang, uninstalled.id, uninstalled.name) });
  return fill(s.bootPc);
}

export function cheerLine(lang: Lang, place: number, name: string): string {
  const s = screen(lang);
  const nameSafe = name;
  if (place === 1) return s.cheer1.replace("{name}", nameSafe);
  if (place === 2) return s.cheer2.replace("{name}", nameSafe);
  if (place === 3) return s.cheer3.replace("{name}", nameSafe);
  if (place > 3) return s.cheerN.replace("{place}", String(place)).replace("{name}", nameSafe);
  return s.cheer0.replace("{name}", nameSafe);
}

const ORD: Partial<Record<Lang, [string, string, string]>> = {
  es: ["1.º", "2.º", "3.º"],
  uk: ["1-й", "2-й", "3-й"],
  ru: ["1-й", "2-й", "3-й"],
  ar: ["الأول", "الثاني", "الثالث"],
  "fa-AF": ["اول", "دوم", "سوم"],
  rw: ["wa mbere", "wa kabiri", "wa gatatu"],
  ti: ["1ይ", "2ይ", "3ይ"],
};

export function placeWord(lang: Lang, n: number): string {
  const row = ORD[lang];
  if (n === 1) return row?.[0] ?? "1st";
  if (n === 2) return row?.[1] ?? "2nd";
  if (n === 3) return row?.[2] ?? "3rd";
  return lang === "en" || lang === "simple" ? `${n}th` : String(n);
}

const CLOSE_LABEL: Record<string, string> = {
  en: "Close",
  simple: "Close",
  es: "Cerrar",
  uk: "Закрити",
  ru: "Закрыть",
  ar: "إغلاق",
  "fa-AF": "بستن",
  rw: "Funga",
  ti: "ዕጸው",
};

export function closeLabel(lang: string) {
  return CLOSE_LABEL[lang] || "Close";
}
